dist: focal

language: php

php:
  - 7.3

before_script:
  - sudo apt-cache search php  # Print available PHP versions
  - php -v  # Print current PHP version
  - phpenv versions  # List available PHP versions
  - phpenv global 7.3  # Try setting the version

script:
  - true
