dist: focal

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libxml2-dev

install:
  # Download and extract PHP 7.3
  - wget https://www.php.net/distributions/php-7.3.*/tar.gz -O php-7.3.tar.gz
  - tar -xzvf php-7.3.tar.gz
  - cd php-7.3.*

  # Configure, make, and install PHP
  - ./configure
  - make
  - sudo make install

  # Go back to the project root directory
  - cd $TRAVIS_BUILD_DIR

script:
  - php --version
