language: ruby
dist: bionic
branches:
  only:
    - main
before_install:
  - eval $(ssh-agent -s)
  - ssh-add - <<< $debase_deploy_key
  - sudo rm -f /etc/apt/sources.list.d/pgdg.list
  - rvm use 2.4.0 --install --binary --fuzzy
script:
  - bundle install
